"""Bundle the tracked source files into docs/assets/code-snapshot.js for the project site's code viewer.

GitHub Pages only serves docs/, so the code page reads this snapshot instead of linking to GitHub.
Re-run after changing source files:  python tools/build_code_snapshot.py
"""

import json
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "assets" / "code-snapshot.js"
SUFFIXES = (".py", ".yaml", ".toml")
EXCLUDE_PREFIXES = ("docs/", "outputs/", "wandb/", "data/", "tools/")


def tracked_files():
    out = subprocess.run(["git", "ls-files"], cwd=ROOT, check=True, capture_output=True, text=True).stdout
    return sorted(p for p in out.splitlines() if p.endswith(SUFFIXES) and not p.startswith(EXCLUDE_PREFIXES))


def main():
    files = [{"path": p, "text": (ROOT / p).read_text(encoding="utf-8")} for p in tracked_files()]
    body = json.dumps({"files": files}, ensure_ascii=False, separators=(",", ":"))
    OUT.write_text("// Generated by tools/build_code_snapshot.py; do not edit by hand\n"
                   f"window.CODE_SNAPSHOT = {body};\n", encoding="utf-8")
    print(f"{len(files)} files, {OUT.stat().st_size / 1024:.0f} KiB -> {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
